import { Poppins, Anton_SC, Playwrite_US_Trad } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const antonSC = Anton_SC({
  variable: "--font-anton-sc",
  subsets: ["latin"],
  weight: "400",
});

const playwriteUSTrad = Playwrite_US_Trad({
  variable: "--font-playwrite-us-trad",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      suppressHydrationWarning
      lang="en"
      className={`${poppins.variable} ${antonSC.variable} ${playwriteUSTrad.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground font-poppins">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
