import { Poppins, Anton_SC, Playwrite_US_Trad, Alex_Brush } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import SmoothScroll from "@/components/smooth-scroll/SmoothScroll";
import Loader from "@/components/loader/Loader";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const antonSC = Anton_SC({
  variable: "--font-anton-sc",
  subsets: ["latin"],
  weight: "400",
});

const playwriteUSTrad = Playwrite_US_Trad({
  variable: "--font-playwrite-us-trad",
  weight: "400",
});

const alexBrush = Alex_Brush({
  variable: "--font-alex-brush",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      suppressHydrationWarning
      lang="en"
      className={`${poppins.variable} ${antonSC.variable} ${playwriteUSTrad.variable} ${alexBrush.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground font-poppins">
        <Loader />
        <SmoothScroll>
          <Navbar />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
